GET http://localhost:8081/hello?name=shankar


POST http://localhost:8081/api/courses
Content-Type: application/json

{
   "id" :7,
    "name":"course7" ,
    "author":"zeus"
}

DELETE    http://localhost:8081/api/courses/1
